# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'db_table': 'attr',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='brands', verbose_name='Фото')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Брэнд',
                'verbose_name_plural': 'Брэнды',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='category', verbose_name='Фото')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('brands', models.SmallIntegerField(verbose_name='Бренды')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(blank=True, default=0, verbose_name='Товар')),
                ('attr', models.IntegerField(blank=True, default=0, verbose_name='Атрибут')),
                ('value', models.CharField(max_length=250, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category', models.IntegerField(verbose_name='Категория')),
                ('brand', models.IntegerField(verbose_name='Бренд')),
                ('parent', models.IntegerField(blank=True, default=0, verbose_name='Основной товар')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/thamb', verbose_name='Превью')),
                ('slide', models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/slide', verbose_name='Слайды')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('old_price', models.FloatField(blank=True, default=0, verbose_name='Старая цена')),
                ('visible', models.SmallIntegerField(blank=True, default=1, verbose_name='Видимость на сайте')),
                ('hit', models.SmallIntegerField(blank=True, default=0, verbose_name='Хит продаж')),
                ('new', models.SmallIntegerField(blank=True, default=0, verbose_name='Новинка')),
                ('sale', models.SmallIntegerField(blank=True, default=0, verbose_name='Распродажа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
    ]
