# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Atribute',
                'verbose_name_plural': 'Atributes',
                'db_table': 'attr',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='brand', verbose_name='photo')),
                ('country', models.CharField(max_length=250, verbose_name='country')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='category', verbose_name='photo')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='Value')),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Attr')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('title', models.CharField(blank=True, default='', max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('img', models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/thamb', verbose_name='Preview')),
                ('slide', models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/slide', verbose_name='Slides')),
                ('text', models.TextField(blank=True, default='', verbose_name='Text')),
                ('currency', models.CharField(max_length=10, verbose_name='Carrence')),
                ('price', models.FloatField(verbose_name='Price')),
                ('old_price', models.FloatField(blank=True, null=True, verbose_name='Old price')),
                ('visible', models.BooleanField(default=True, verbose_name='Viseble')),
                ('hit', models.BooleanField(default=False, verbose_name='Hit')),
                ('new', models.BooleanField(default=False, verbose_name='New')),
                ('sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='options',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
