# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attr',
            options={'verbose_name': 'Atribute', 'verbose_name_plural': 'Atributes'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='attr',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='country',
            field=models.CharField(max_length=250, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='img',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='brands', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='brands',
            field=models.SmallIntegerField(verbose_name='brands'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='category', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='options',
            name='attr',
            field=models.IntegerField(blank=True, default=0, verbose_name='Atribute'),
        ),
        migrations.AlterField(
            model_name='options',
            name='product',
            field=models.IntegerField(blank=True, default=0, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='options',
            name='value',
            field=models.CharField(max_length=250, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.IntegerField(verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(max_length=10, verbose_name='Carrence'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hit',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Hit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/thamb', verbose_name='Preview'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Old price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Base product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slide',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='clothes/slide', verbose_name='Slides'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='visible',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='Viseble'),
        ),
    ]
